# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: false
      addresses:
      - 192.168.200.3/24
      routes:
      - to:  0.0.0.0/0
        via: 192.168.200.1
      nameservers:
        addresses:
           - 8.8.8.8
  version: 2

